#!/usr/bin/env bash
# shellcheck disable=SC2059
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 6)
#RED=$(tput setaf 1)
NC=$(tput sgr 0)
set -e
readonly TEX_DIR="/home/$USER/texmf/tex/latex/"
function convert_eps_files()
{
  if [ -e eps2pdf.sh ]; then
    sh -c "./eps2pdf.sh"
  else
    printf "File eps2pdf.sh is missing. Did you clone the repository properly?\n"
    exit 1;
  fi
}

function copy_files()
{
  mkdir -p "$TEX_DIR"
  if command -v rsync >&/dev/null; then
    printf "${BLUE}Copying files to ${YELLOW} ${TEX_DIR}/europass-cv...${NC}\n"
    rsync -Ea --recursive --exclude='*.md*' --exclude='*.MD*' --exclude europass-cv-compact.cls ./ "${TEX_DIR}/europass-cv" && printf "${YELLOW}[ INFO ]${NC} Copied Files.\n"
    printf "${BLUE}Copying files to ${YELLOW} ${TEX_DIR}/europass-cv-compact...${NC}\n"
    rsync -Ea --recursive --exclude='*.md*' --exclude='*.MD*' --exclude europass-cv.cls ./ "${TEX_DIR}/europass-cv-compact" && printf "${YELLOW}[ INFO ]${NC} Copied Files.\n"

  else
    printf "${YELLOW}Program rsync is not installed. Please install rsync.\nThis script requires rsync.\n${NC}";
  exit 1;
  fi
}

function  change_branch()
{
  if [ $# -eq 0 ]; then
    printf "\n${YELLOW}No arguments found. Chosing master branch.\n${NC}"
    git checkout master
  else
    printf "\n${YELLOW}Chosing branch: ${1} \n${NC}"
    git checkout "$1"
  fi
}

function main ()
{
  #change_branch "$@"
  convert_eps_files
  copy_files
  printf "${BLUE}Updating Texhash...${NC}\n"
  texhash $TEX_DIR
}

main "$@"
