version: 1
update_configs:
  # Keep Dockerfile up to date, batching pull requests weekly
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "dev"
    default_reviewers:
      - "tprasadtp"
    default_labels:
      - "Meta: Automation"
      - "Actor: Dependabot"
      - "Type: Dependencies"
      - "Deps: Docker"
    automerged_updates:
      - match:
          update_type: "semver:patch"
    commit_message:
      prefix: "Maintainance"
      include_scope: true
    allowed_updates:
      - match:
          update_type: "security"